# Example file: https://github.com/cncf/gitvote/blob/main/docs/config/.gitvote.yml
profiles:
  default:
    duration: 1m
    pass_threshold: 66
    allowed_voters:
      users:
        - Burning1020
      exclude_team_maintainers: true
